<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-6G93JPF" failures="2" tests="3" name="Test(failed)(failed)" time="0.093" errors="0" timestamp="2022-01-02T19:00:42 IST">
  <testcase classname="Demo.Failed_testCase" name="TC3" time="0.012"/>
  <testcase classname="Demo.Failed_testCase" name="TC5" time="0.004">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at Demo.Failed_testCase.TC5(Failed_testCase.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC5 -->
  <testcase classname="Demo.Failed_testCase" name="TC2" time="0.001">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at Demo.Failed_testCase.TC2(Failed_testCase.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC2 -->
  <testcase classname="Demo.Failed_testCase" name="TC1" time="0.0">
    <ignored/>
  </testcase> <!-- TC1 -->
  <testcase classname="Demo.Failed_testCase" name="TC4" time="0.0">
    <ignored/>
  </testcase> <!-- TC4 -->
</testsuite> <!-- Test(failed)(failed) -->
